import Link from "next/link";
import TopNavbar from "./components/TopNavbar/TopNavbar";

export default function Home() {
  return (
    <>
      <TopNavbar />
      <div className="min-h-screen bg-gradient-to-br from-emerald-50 to-blue-100">
      <section className="relative px-6 lg:px-8 py-24 sm:py-32">
        <div className="mx-auto max-w-4xl text-center">
          <div className="mb-8">
            <div className="inline-flex items-center rounded-full bg-emerald-100 px-4 py-2 text-sm font-medium text-emerald-800 mb-6">
              <span className="mr-2">🎓</span>
              Jackson State University Senior Project
            </div>
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl">
            <span className="text-emerald-600">Entrepreneurial Hub</span>
            <br />
            Business Assessment Platform
          </h1>
          <p className="mt-6 text-lg leading-8 text-gray-600 max-w-3xl mx-auto">
            Evaluate your business's digital maturity with AI-powered assessments. Get personalized 
            recommendations, track your progress, and unlock resources to grow your entrepreneurial 
            venture with confidence.
          </p>
          <div className="mt-10 flex items-center justify-center gap-x-6">
            <Link
              href="/dashboard"
              className="rounded-md bg-emerald-600 px-6 py-3 text-lg font-semibold text-white shadow-sm hover:bg-emerald-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600 transition-all duration-200 transform hover:scale-105"
            >
              Start Assessment
            </Link>
            <Link
              href="/about"
              className="text-lg font-semibold leading-6 text-gray-900 hover:text-emerald-600 transition-colors duration-200"
            >
              Learn more <span aria-hidden="true">→</span>
            </Link>
          </div>
        </div>
      </section>

      <section className="py-24 bg-white">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
              Comprehensive Entrepreneurial Assessment
            </h2>
            <p className="mt-4 text-lg leading-8 text-gray-600">
              Our AI-powered platform evaluates multiple aspects of your entrepreneurial venture to provide 
              actionable insights and personalized growth strategies for success.
            </p>
          </div>
          <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
            <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
              <div className="flex flex-col group hover:bg-gray-50 p-6 rounded-xl transition-all duration-300">
                <dt className="flex items-center gap-x-3 text-base font-semibold leading-7 text-gray-900">
                  <div className="h-12 w-12 flex items-center justify-center rounded-lg bg-gradient-to-r from-emerald-500 to-emerald-600 group-hover:scale-110 transition-transform duration-300">
                    <span className="text-white font-bold text-lg">AI</span>
                  </div>
                  AI-Powered Questions
                </dt>
                <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-gray-600">
                  <p className="flex-auto">
                    Get tailored questions specific to your industry and entrepreneurial venture, 
                    generated by advanced AI to assess your unique business situation and potential.
                  </p>
                </dd>
              </div>
              <div className="flex flex-col group hover:bg-gray-50 p-6 rounded-xl transition-all duration-300">
                <dt className="flex items-center gap-x-3 text-base font-semibold leading-7 text-gray-900">
                  <div className="h-12 w-12 flex items-center justify-center rounded-lg bg-gradient-to-r from-blue-500 to-blue-600 group-hover:scale-110 transition-transform duration-300">
                    <span className="text-white font-bold text-xl">📊</span>
                  </div>
                  Smart Scoring System
                </dt>
                <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-gray-600">
                  <p className="flex-auto">
                    Receive detailed scores on digital maturity, business readiness, and 
                    compliance with categorization into Beginner, Growing, or Established entrepreneur tiers.
                  </p>
                </dd>
              </div>
              <div className="flex flex-col group hover:bg-gray-50 p-6 rounded-xl transition-all duration-300">
                <dt className="flex items-center gap-x-3 text-base font-semibold leading-7 text-gray-900">
                  <div className="h-12 w-12 flex items-center justify-center rounded-lg bg-gradient-to-r from-purple-500 to-purple-600 group-hover:scale-110 transition-transform duration-300">
                    <span className="text-white font-bold text-xl">📈</span>
                  </div>
                  Progress Tracking
                </dt>
                <dd className="mt-4 flex flex-auto flex-col text-base leading-7 text-gray-600">
                  <p className="flex-auto">
                    Track your entrepreneurial development over time with stored results, 
                    exportable reports, and follow-up assessments to measure your business growth.
                  </p>
                </dd>
              </div>
            </dl>
          </div>
        </div>
      </section>

      <section className="py-24 bg-gray-50">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
              How It Works
            </h2>
            <p className="mt-4 text-lg leading-8 text-gray-600">
              Simple steps to assess and improve your entrepreneurial venture
            </p>
          </div>
          <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
            <div className="grid max-w-xl grid-cols-1 gap-8 lg:max-w-none lg:grid-cols-4">
              <div className="text-center group">
                <div className="mx-auto h-16 w-16 flex items-center justify-center rounded-full bg-gradient-to-r from-emerald-500 to-emerald-600 text-white font-bold text-xl mb-4 group-hover:scale-110 transition-transform duration-300 shadow-lg">
                  1
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Sign Up</h3>
                <p className="text-gray-600">
                  Create your account and enter your entrepreneurial venture information
                </p>
              </div>
              <div className="text-center group">
                <div className="mx-auto h-16 w-16 flex items-center justify-center rounded-full bg-gradient-to-r from-blue-500 to-blue-600 text-white font-bold text-xl mb-4 group-hover:scale-110 transition-transform duration-300 shadow-lg">
                  2
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Assessment</h3>
                <p className="text-gray-600">
                  Answer AI-generated questions tailored to your industry and business model
                </p>
              </div>
              <div className="text-center group">
                <div className="mx-auto h-16 w-16 flex items-center justify-center rounded-full bg-gradient-to-r from-purple-500 to-purple-600 text-white font-bold text-xl mb-4 group-hover:scale-110 transition-transform duration-300 shadow-lg">
                  3
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Results</h3>
                <p className="text-gray-600">
                  Get your entrepreneurial readiness score and personalized recommendations
                </p>
              </div>
              <div className="text-center group">
                <div className="mx-auto h-16 w-16 flex items-center justify-center rounded-full bg-gradient-to-r from-orange-500 to-orange-600 text-white font-bold text-xl mb-4 group-hover:scale-110 transition-transform duration-300 shadow-lg">
                  4
                </div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Grow</h3>
                <p className="text-gray-600">
                  Access resources, mentorship opportunities, and track your progress over time
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-gradient-to-r from-emerald-600 to-blue-600 py-24">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="text-3xl font-bold tracking-tight text-white sm:text-4xl">
              Ready to Launch Your Entrepreneurial Journey?
            </h2>
            <p className="mt-6 text-lg leading-8 text-emerald-100">
              Join students and entrepreneurs who are using Entrepreneurial Hub to evaluate 
              and improve their business strategies with AI-powered insights and expert guidance.
            </p>
            <div className="mt-10 flex items-center justify-center gap-x-6">
              <Link
                href="/dashboard"
                className="rounded-md bg-white px-6 py-3 text-lg font-semibold text-emerald-600 shadow-lg hover:bg-gray-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white transition-all duration-200 transform hover:scale-105"
              >
                Get Started Now
              </Link>
              <Link
                href="/contact"
                className="text-lg font-semibold leading-6 text-white hover:text-emerald-100 transition-colors duration-200"
              >
                Contact Us <span aria-hidden="true">→</span>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <footer className="bg-gray-900 py-12">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-center">
            <div className="text-white text-xl font-bold mb-4 bg-gradient-to-r from-emerald-400 to-blue-400 bg-clip-text text-transparent">
              Entrepreneurial Hub
            </div>
            <p className="text-gray-400 mb-6 text-lg">
              Empowering entrepreneurs with AI-powered business assessments and growth strategies
            </p>
            <div className="grid grid-cols-1 md:grid-cols-5 gap-4 justify-center text-sm text-gray-400 mb-8">
              <div className="bg-gray-800 p-3 rounded-lg hover:bg-gray-700 transition-colors duration-200">
                <div className="font-semibold text-emerald-400">Cybersecurity Lead</div>
                <div>Kaniyah White</div>
              </div>
              <div className="bg-gray-800 p-3 rounded-lg hover:bg-gray-700 transition-colors duration-200">
                <div className="font-semibold text-blue-400">Software Engineering Lead</div>
                <div>Marlvin Goremusandu</div>
              </div>
              <div className="bg-gray-800 p-3 rounded-lg hover:bg-gray-700 transition-colors duration-200">
                <div className="font-semibold text-purple-400">Database Lead</div>
                <div>Kaylen Bolden</div>
              </div>
              <div className="bg-gray-800 p-3 rounded-lg hover:bg-gray-700 transition-colors duration-200">
                <div className="font-semibold text-orange-400">Project Manager Lead</div>
                <div>Jaylon Nelson</div>
              </div>
              <div className="bg-gray-800 p-3 rounded-lg hover:bg-gray-700 transition-colors duration-200">
                <div className="font-semibold text-pink-400">Programming Lead</div>
                <div>Sa'Nya Griffin</div>
              </div>
            </div>
            <div className="mt-8 pt-8 border-t border-gray-800 text-center text-sm text-gray-400">
              <p>&copy; 2025 Entrepreneurial Hub - Jackson State University. All rights reserved.</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
    </>
  );
}
